services:
  redis:
    image: "redis:alpine"
  
  backend:
    build: ./backend
    ports:
      - "0.0.0.0:8001:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    env_file: .env
    volumes:
      - ./data:/app/data
    depends_on:
      - redis
